POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 2020,
    "mileage": 15000,
    "price": 20000,
    "lng": 0,
    "lat": 0
}

### Approve an existing report
PATCH http://localhost:3000/reports/7
content-type: application/json

{
    "approved": true
}